spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/books?serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081

jwt:
  rsaKeySize: 2048
  expired: 5
  issuer: SCUT-SE
request:
  uri:
    login: /login
  header:
    authority: jwt


---
spring:
     profiles: dev

my:
  name: pentix
---
spring:
     profiles:test
my:
  name: kirhhoff
---
spring:
     profiles:release
my:
  name: northy
