spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/SE_backend?serverTimezone=GMT
    username: root
    password: 240036
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8081

jwt:
  rsaKeySize: 2048
  expired: 5
  issuer: SCUT-SE
default:
  password: 123456


---
spring:
     profiles: dev

my:
  name: pentix
---
spring:
     profiles:test
my:
  name: kirhhoff
---
spring:
     profiles:release
my:
  name: northy
